### PR TITLE
add support to go fullscreen with a double-click

### PR DESCRIPTION
**Pull request by arose**
nice touch as it is mentioned in the blog post

### CODE REVIEW

**Comment by dotsdl** [comment]
Hmmm...can't get this to work using jekyll locally. Is something missing?

**Comment by arose** [comment]
Oh, you're using a rather old version that does not include the `stage.toggleFullscreen` method. Currently it is probably best to use the build from the dev branch https://github.com/arose/ngl/blob/dev/js/build/ngl.embedded.min.js. Hope to do the 0.7 release sometime soon.

**Comment by dotsdl** [comment]
Ah gotcha. Would you mind slotting the latest and greatest one into [`js/build/ng.embedded.min.js`](https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/js/build/ngl.embedded.min.js) in this PR? Then I think we'll be good to merge.

**Comment by arose** [comment]
just updated it, but is untested, so please give it a try before merging. thanks

**Comment by dotsdl** [comment]
Works like a charm. :D

**Comment by dotsdl** [comment]
Thanks @arose !

**Comment by hainm** [comment]
@dotsdl if you want to make MDA more impressive, you can make a trajectory viewer with play button too. :P

**Comment by dotsdl** [comment]
@hainm Not sure what you mean. The site is static, so hosting trajectory iteration wouldn't work, I don't think.

**Comment by hainm** [comment]
>  The site is static

uhm, you catch me. forgot about the 'static.

**Pull request merged**
