### PR TITLE
Conda (fixes #20)

### LINKED ISSUE #20: add conda installation instructions
Once PR MDAnalysis/mdanalysis#751 is merged, which makes MDAnalysis available through `conda` MDAnalysis/mdanalysis#608 , we need to document this
- [x] add to Quickstart Installation
- [x] blog post

Also update the tutorial (MDAnalysis/MDAnalysisTutorial#7).

### PR DESCRIPTION
**Pull request by kain88-de**
Fixes #20 

After merging the build instructions it's time to make the conda build official. Here is the release text for the blog post and the changed quick install instructions.

### CODE REVIEW

**Comment by kain88-de** [comment]
Question. How can I link to the quickinstall on the website from inside of a blog post?

**Comment by orbeckst** [comment]
Links inside need to be written as full links from the baseurl
```
{{site.baseurl}}pages/installation_quick_start.md
```
See https://github.com/MDAnalysis/MDAnalysis.github.io#notes-on-using-jekyll ; for some often used directories we have variables in _config.xml (but you still need `{{site.baseurl}}`).

If you want to refer to a blog post there are other ways, eg using the liquid tag [post_url](https://jekyllrb.com/docs/templates/#post-url)
```
{{site.baseurl}}{% post_url 2016-02-28-release-0.14.0 %}
```

**Comment by orbeckst** [comment]
ping me when ready

**Comment by kain88-de** [comment]
@orbeckst changed all links

**Comment by kain88-de** [comment]
Lets wait til tomorrow with publishing since that is the date I set and I can look for possible spelling errors again.

**Comment by orbeckst** [comment]
I could merge now because it will only publish on the date (when it rebuilds on the next push).
Just merge tomorrow, I am assigning you.

**Comment by orbeckst** [comment]
Just did some minor changes and checked with
```
bundle exec jekyll serve --watch --force_polling
```
and everything looks good! (merge whenever you want to!)

**Comment by orbeckst** [comment]
btw, I have no idea how to change the Anaconda MDAnalysis org picture – right now it shows my mugshot...

**Pull request merged**
