### PR TITLE
blog post about projects using MDA

### LINKED ISSUE #63: List of projects using MDAnalysis
It would be good to have a list of projects on the website that use MDAnalysis.

from others

- [pytim](https://marcello-sega.github.io/pytim/)
- [pycontact](https://github.com/maxscheurer/pycontact)
- [nglview](https://github.com/arose/nglview)
- [pycazip](https://www.sciencedirect.com/science/article/pii/S2352711016300036)

Ours

-  [RotamerConvolveMD](https://github.com/MDAnalysis/RotamerConvolveMD)

I'm sure I forgot a lot. It would be nice if others could extend that list.

### PR DESCRIPTION
**Pull request by kain88-de**
fixes #63

### CODE REVIEW

**Comment by kain88-de** [comment]
Note I haven't tried to render this with jekyll yet.

**Comment by richardjgowers** [comment]
Maybe this is better as a static page not a blogpost?

**Comment by orbeckst** [comment]
I am fine with a blog post as it represents a snapshot, at least for right now. 

We could turn it into a static page eventually. But let's start with a post.

**Comment by orbeckst** [comment]
@kain88-de if you change the date then we can publish this post _before_ the GSoD post PR #99 and we can just link to this post. I think that would work even better than explicitly mentioning a few tools.

**Comment by kain88-de** [comment]
date is updated. The post can go live

**Pull request merged**
