### PR TITLE
start GSOC 2018 student blog post

### LINKED ISSUE #70: Blog post for GSOC 2018
- [ ] people 
- [ ] pictures
- [ ] projects

Use last year's post as a template https://github.com/MDAnalysis/MDAnalysis.github.io/blob/master/_posts/2017-06-04-gsoc-students.md

### PR DESCRIPTION
**Pull request by orbeckst**
- close #70
- added stubs for @ayushsuhane and @davidercruz
- TODO
  - [x] link to real pictures
  - [x] links to student blogs
  - [x] make sure link to numfocus GSOC 2018 blog exists...
  - [x] add short bios
  - [ ] add links to content inside the science part
  - [ ] expand science part

### CODE REVIEW

**Comment by orbeckst** [comment]
@davidercruz and @ayushsuhane congratulations on being selected for GSOC 2018! We're glad to have you on board. 

We want to announce your projects on the MDAnalysis blog, similar to what we did [last year](https://www.mdanalysis.org/2017/06/04/gsoc-students/). Can you please supply the following (you can do a PR against this branch or add something in the comments):
- [ ] short bio (up to about 4 sentences about who you are and what you do)
- [ ] link to your GSOC blog
- [ ]  abstract on your project (I just pasted from the GSOC announcement, but feel free to expand)
- [ ] picture (or update your GitHub avatar) – *optional*, if you don't want your picture displayed then we won't force you

**Comment by orbeckst** [comment]
@davidercruz thanks for the update, updating your avatar, **and setting up your blog**.

**Comment by orbeckst** [comment]
Looks good to me – @jbarnoud and @richardjgowers are you happy to publish it (and of course tweet...)?

**Comment by richardjgowers** [comment]
Yeah LGTM @jbarnoud ?

**Pull request merged**
