### PR TITLE
Blog post for 0.17.0

### PR DESCRIPTION
**Pull request by jbarnoud**
Let's get prepared.

### CODE REVIEW

**Comment by kain88-de** [comment]
I updated the contributions. This lists Max as well in the development of the new libdcd library and removes the mentioning of the TravisCI speedup which was mostly due to changes in the
Travis setup by Max. The  tests run faster now as well but Travis was a hell lot faster before we started to switch to pytest.

**Comment by kain88-de** [comment]
short noteworthy list of additions that aren't in the post yet.

- [ ] GSD Format addition
- [ ] new dcd reader
- [ ] pickle support for dcd and xtc files for pmda
- [ ] various speed improvements
- [ ] molnums/moltypes for tpr
- [ ] Model Building (add_topologyAttr / Universe.empty )

**Comment by richardjgowers** [comment]
Txyz format too

**Comment by kain88-de** [comment]
IS that in the changelog? It's definitely in the post already. I'm doing a short rework right now.

**Comment by kain88-de** [comment]
@jbarnoud and @richardjgowers do you want to write about the new topology improvements? With TPR and the empty universe. 

Now, this version contains the most interesting new features as I see them. Feel free to add more if you think I missed some.

I'm going on a retreat tomorrow so I can't edit this any further.

We should also wait to publish this blog post until the conda builds are done. This could take a little while right now. Travis has a lot of mac os errors

**Comment by kain88-de** [comment]
@jbarnoud or @richardjgowers could you fill in the last gaps and read over the post. That would be nice thank you.

All channels now have the updated version of MDAnalysis.

**Comment by orbeckst** [comment]
- We should also mention the periodic KDTree for geometric selections.
- For testing: we have 91% coverage (this is good for a big project, definitely worth mentioning!)
- new water bridge analysis module

Other things:
- Perhaps point out the fixes for triclinic boxes? Or leave this to the people reading CHANGELOG?
- Whole bunch of removals for deprecated functions (`mass_weighted` keyword, use `weights="mass"` instead, removed `core.Timeseries`)

**Comment by richardjgowers** [comment]
Ok I'll add some quick examples of `Universe.empty` soon

**Comment by richardjgowers** [comment]
Ok should be good to go

**Comment by kain88-de** [comment]
I’m almost ok with the post. I think we need to update the publishing date. 

Otherwise it’s good. We acknowledge new contributors and have a few highlights.

**Comment by kain88-de** [comment]
I updated the post date to tomorrow. If there are no more complaints I would publish it tomorrow.

**Comment by orbeckst** [comment]
Looks really good. Thank you all!

--
Oliver Beckstein
email: orbeckst@gmail.com

**Pull request merged**
