### PR TITLE
drafted blog post for GSOC 2019

### PR DESCRIPTION
**Pull request by orbeckst**
Blog needed for advertising GSOC 2019 #96

### CODE REVIEW

**Comment by orbeckst** [comment]
@richardjgowers @micaela-matta @jbarnoud can you please have a quick look at the post? I copied and edited the one from last year. 
* added note on Code of Conduct
* updated deadline and opening of application window
* signed with the handles of all four mentors

I'd like to let this go live on Monday if possible. Then we can send out email/tweet.

**Comment by orbeckst** [comment]
oops. sorry @richardjgowers – there was a new button with two circular arrows on you as a reviewer and I do when one sees a button: I pressed it. Apparently it asks for a re-review. Well, that's not needed, thank you for your read-through and 'lgtm'. Apologies for the extra hassle.

**Comment by richardjgowers** [comment]
Haha the “click shiny buttons” approach to software development
  

  
  

  
  
>

**Comment by orbeckst** [comment]
Richard,

Thanks. Can you do the advertising (emails/tweet) please? I am busy today.

Many thanks!
Oliver

**Comment by richardjgowers** [comment]
Yep, on it
  

  
  

  
  
>

**Comment by orbeckst** [comment]
Ta!

**Pull request merged**
