### PR TITLE
Gsoc 2017

### PR DESCRIPTION
**Pull request by kain88-de**
This is the announcement post for this year. If you could look if I missed some changes that would be nice.

### CODE REVIEW

**Comment by orbeckst** [comment]
Add NumFOCUS logo?

**Comment by kain88-de** [comment]
I'll add the NumFOCUS logo later

**Comment by kain88-de** [comment]
The numfocus logo is added. I will have no internet the next couple of days. So just merge this if you like it.

**Comment by orbeckst** [comment]
@philipwfowler et al: tweet?

--
Oliver Beckstein
email: orbeckst@gmail.com

**Pull request merged**
