### PR TITLE
add new coredevs

### PR DESCRIPTION
**Pull request by orbeckst**
- [x] add newly elected @fiona-naughton and @micaela-matta to official core devs list (this PR)
- [x] add new core devs to @MDAnalysis/coredevs 
- [x] add to Discord coredevs group (@IAlibay must do this)
- [ ] announce on developer list
- [ ] tweet

### CODE REVIEW

**Review by IAlibay — APPROVED** [review]
lgtm

**Review by lilyminium — APPROVED** [review]
LGTM

**Review by jbarnoud — APPROVED** [review]
LGTM

**Comment by orbeckst** [comment]
Congratulations @fiona-naughton and @micaela-matta , you're officially @MDAnalysis/coredevs .

**Pull request merged**
