### PR TITLE
GSoD 2019 final blog post

### PR DESCRIPTION
**Pull request by orbeckst**
- link to @lilyminium's blog
- link to User Guide and Quickstart Guide

### CODE REVIEW

**Comment by orbeckst** [comment]
@richardjgowers and @lilyminium please feel free to edit

**Comment by orbeckst** [comment]
Note that I already updated https://www.mdanalysis.org/pages/learning_MDAnalysis/ so that Quick Start Guide and User Guide are the first things for new users. More edits are welcome, too.

@lilyminium I am using your delightful GSoD+MDA logo from your blog post. I hope that's ok. At the moment, I use a link but we could just add it locally in images.

**Comment by orbeckst** [comment]
Well... technically, they'd say no: https://developers.google.com/season-of-docs/docs/press (see logo section). 

I am pretty sure that no-one will ever complain but to play it safe for MDA I'll continue to just link to your logo – If you decide to change it, we also need to change the link here and revert it to the official one.

**Comment by lilyminium** [comment]
Oops. 😨

**Comment by orbeckst** [comment]
Let's merge this tomorrow.

**Pull request merged**
