### PR TITLE
The 0.14.0 release blog-post

### PR DESCRIPTION
**Pull request by kain88-de**
Lets start the next blog post text early. I think it can also serve as an announcement mail for the next release, or we just link to the blog post.

If you think you made a big change to the library and want to explain it in more detail this is the right place.

### CODE REVIEW

**Comment by richardjgowers** [comment]
So this is a quasi WIP branch that we merge on release?

**Comment by kain88-de** [comment]
Yes that's what I thought.

**Comment by orbeckst** [comment]
Please double check and then someone else can make it go live.

(Do you want to keep this PR around and then merge & reopen?)

**Comment by orbeckst** [comment]
@richardjgowers can you announce to the list once everything is life?

@philipwfowler can then handle the "social" aspects, i,e,, tweet etc.

**Comment by kain88-de** [comment]
I changed the wording a little bit. Otherwise it reads nice to me and it shows of the new features very nicely.

**Comment by orbeckst** [comment]
As far as I'm concerned it's good to go. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Feb 28, 2016 um 13:45 schrieb kain88-de <notifications@github.com>:

**Comment by orbeckst** [comment]
Blog post live

**Comment by richardjgowers** [comment]
Mailing list done

**Comment by philipwfowler** [comment]
And tweeted. Will tweet again this pm for US time. 

—Phil

**Comment by orbeckst** [comment]
Thanks!

Now onwards an upwards (ie, towards getting MDAnalysis/mdanalysis#363 in). 

Are we going to re-use the next-release branch for the next blog post?

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Feb 29, 2016 um 2:45 schrieb Richard Gowers <notifications@github.com>:

**Comment by kain88-de** [comment]
I regenerated the branch now. Could be that you need to force-update. Plain reusing and rebasing onto master would be better next time.

**Pull request merged**
