### PR TITLE
GSoD post

### PR DESCRIPTION
**Pull request by orbeckst**
This post can be linked from twitter etc in order to attract technical writers.

- link to previous posts for details
- try to attract writers
- link to a MD video for eye candy (alternatives)? https://www.youtube.com/embed/VpkOPmzlZco
- fixed heading level in previous post

### CODE REVIEW

**Comment by orbeckst** [comment]
@richardjgowers @kain88-de please have a look. If possible I'd like it up tomorrow and be able to link to it.

**Comment by kain88-de** [comment]
Might make sense to market this on LinkedIn as well.

**Comment by richardjgowers** [comment]
@orbeckst I made a few changes, but looks good - https://github.com/MDAnalysis/MDAnalysis.github.io/pull/102/commits/53262613e796264c4e191052f4ce54d44c9df0a1

**Comment by orbeckst** [comment]
Many thanks you two!

**Pull request merged**
