### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by lilyminium**
Fixes this security alert: https://discord.com/channels/807348386012987462/808088547894231111/1133883281495040100

### CODE REVIEW

**Review by IAlibay — APPROVED** [review]
I know it's tthe right fix, I just don't want to check the build, so trusting you've checked 🙃

**Comment by lilyminium** [comment]
I think the patch suggestion is inaccurate -- there is no webrick 2.2.8. I think it's meant to be the Ruby version. This builds locally for me.

**Comment by IAlibay** [comment]
Would it have been at least worth updating to webricks 1.8.1?

**Comment by lilyminium** [comment]
Sure, we can do that in another PR -- I was somewhat nervous merging this one as it is so kept changes minimal.

**Pull request merged**
