### PR TITLE
add numfocus post

### PR DESCRIPTION
**Pull request by kain88-de**
The current content is relatively short and to the point. Should we add a little bit about the history of the last year and look for projects that are currently using MDAnalysis as well for this post or some other time?

### CODE REVIEW

**Comment by jbarnoud** [comment]
A word about the implication would be nice. Except for that, I think the post goes to the point; the additions you suggest would of course be interesting, but the post can go without.

**Comment by orbeckst** [comment]
Short is fine. Regarding the implications: Although the page says "Support an Affiliated Project" (through a donation) I don't think that we as an affiliated project could actually receive a donation – or can we, @kain88-de ? 

As far as I am concerned, the current implications are that the MDAnalysis project is establishing itself as a part of the wider scientific python eco system and will be able to draw on the experience of NumFOCUS while moving forward.

Not sure if this is worthwhile putting in the post – maybe @kain88-de has something better. 

I would only add the NumFOCUS logo to the post.

**Comment by kain88-de** [comment]
We get some free advertising with this. There is a pydata tweet about mdanalysis now. We should also easier get travel grants from NumFOCUS for conferences.

**Comment by orbeckst** [comment]
Looking good!

**Comment by orbeckst** [comment]
@jbarnoud happy to merge?

**Comment by kain88-de** [comment]
I just have an instinct to check github at exactly the right times.

**Pull request merged**
