### PR TITLE
Adds bage info

### PR DESCRIPTION
**Pull request by mnmelo**
We now have
* a short badge advertising in the index page
* a section under 'Citations' with examples for Markdown, reST and HMTL (to which the GitHub `README.rst` will point)
* and an announcing blog post extolling the virtues of badge-displaying.

### CODE REVIEW

**Comment by mnmelo** [comment]
(I updated the PR description)

For style consistency, I went with a small-case 'powered' in the badge. It seems to be the norm for the left-hand text in badges (vide the NumFOCUS badge, and the others in our own `README.rst`: only proper nouns get left-hand capitalization). I left the tooltip text in title capitals.

I am unsure how best to test the deployment, especially that internal links are working.

**Comment by orbeckst** [comment]
For local testing see https://github.com/MDAnalysis/MDAnalysis.github.io#local-testing — maybe slightly outdated but works for me in principle.

**Comment by orbeckst** [comment]
Good idea to put the badges into citations. I can’t look at the PR in detail right now, overall looking good to me. If you can check a local build yourself and report back then that would be very useful.

**Comment by mnmelo** [comment]
Badges, links, and emojis in the blog post all are working.

The style for the website does not add a horizontal scrolling to code boxes with long lines, and instead wraps the line. This makes the badge URL significantly clutter the page. Worse yet because I am including 3 markup examples. So I used the same html tricks to display-on-demand that I wasn't allowed to use on the project's GitHub `README.rst`. Hopefully they're ok here.

<details>
<summary>Like this (only that in here in GitHub the code box actually does x-scrolling instead of wrapping)</summary>

<pre>
[Powered by MDAnalysis](https://www.mdanalysis.org)
</pre>
</details>

**Review by orbeckst — APPROVED** [review]
Very nice!

I'll merge it. But I have one question: how does the badge help _us_ knowing who uses us? Do we get a ping of some kind when someone installs the badge??

**Comment by mnmelo** [comment]
The easiest is just to use a Google query, exemplified here with the NumFOCUS badge: https://www.google.com/search?q="-NumFOCUS-orange.svg"

**Pull request merged**
