### PR TITLE
update algolia to new index and search box

### LINKED ISSUE #211: migrate DocSearch to Algolia Crawler
algolia (our search provider) recently started migrating search infrastructure. As per email from 11/9/21:

## What do I need to do?

We tried making the migrations as smooth as possible, so all you have to do is:

* [x] Create an Algolia account with your email address if you don't have one yet — @orbeckst with GitHub
* [x] Join your own Algolia application 
* [x] [Update your DocSearch frontend integration](https://docsearch.algolia.com/docs/docsearch-v3/) with your new credentials:
   * Your new appId: Y8HJT3NO22
   * Your new apiKey: 68fa6789d0a275a311f68914e0c2366e (search only key, see [faq](https://docsearch.algolia.com/docs/migrating-from-legacy/#why-is-the-api-key-different-in-the-dashboard))

You can also read more about the [migration](https://docsearch.algolia.com/docs/migrating-from-legacy/) on our documentation or contact us at docsearch@algolia.com or on [Discord](https://discord.com/invite/bRTacwYrfX)

### PR DESCRIPTION
**Pull request by orbeckst**
- use new appId and key (from UI)
- use newer integration with docs from https://github.com/algolia/docsearch
  - new CSS
  - new JS
- closes #211

### CODE REVIEW

**Comment by orbeckst** [comment]
For a preview of the new search box see https://orbeckst.github.io/MDAnalysis.github.io/

**Comment by orbeckst** [comment]
I also updated the [wiki page on search](https://github.com/MDAnalysis/MDAnalysis.github.io/wiki/Search).

**Comment by orbeckst** [comment]
Notes on [styling the search](https://docsearch.algolia.com/docs/styling/).

**Comment by orbeckst** [comment]
Applied minimal styling to make the search box feel a bit more "MDA" 
Screen Shot 2021-11-23 at 4 04 56 PM

This was surprisingly simple with the clean CSS that algolia provides — just pick what you need from [_variables.css](https://github.com/algolia/docsearch/blob/next/packages/docsearch-css/src/_variables.css) and override locally.

**Comment by orbeckst** [comment]
@fiona-naughton @lilyminium @richardjgowers could someone please spare a few minutes to look over this PR? Thanks.

**Review by richardjgowers — APPROVED** [review]

**Pull request merged**
