### PR TITLE
add gsoc 2018 post

### PR DESCRIPTION
**Pull request by kain88-de**
new announcement post for gsoc

### CODE REVIEW

**Comment by kain88-de** [comment]
I plan to publish tomorrow.

**Comment by orbeckst** [comment]
The NumFOCUS logo does not display – I cannot find http://www.numfocus.org/uploads/6/0/6/9/60696727/1457562110.png

My Firefox also complains about mixed content (namely, the http in the above (broken) link).

**Comment by kain88-de** [comment]
@orbeckst they recently updated their website and broke a lot of old links as it looks. Do you mind adding a logo to our repository here and updating the post?

**Comment by orbeckst** [comment]
yes, #67

**Pull request merged**
